Name    = "plurk.smiles"
Author  = "foi"
Date    = "28.02.2009"
Version = "1.0"
;
SelectionSize = 48, 34
WindowSize = 8, 6
Smiley = "angel.gif" , 0, "O:-) O:) O+) O=) 0:-) 0:) 0+) 0=) (A) (a)", "O:-)"
Smiley = "smile.gif" , 0, ":-) :) +) =) :smile:", ":-)"
Smiley = "sad.gif" , 0 ,":-( :( ;( +( =( :-(( :(( +(( =(( :sad:", ":-("
Smiley = "wink.gif" , 0, ";-) ;) ^_~ :wink:", ";-)"
Smiley = "blum.gif" , 0, ":-P :P :-p :p +P =P +p =p :-b :b +b =b :tongue:", ":-P"
Smiley = "dirol.gif", 0, "8-) 8) B) :COOL: :cool: *COOL* COOL!!! (H)", "8-)"
Smiley = "biggrin.gif", 0, ":-D :D +D =D :biggrin:", ":-D"
Smiley = "blush.gif" , 0, ":-[ :[ ;'> ;-. :shy: :blush:", ":-["
Smiley = "shock.gif", 0, "=-O =O =-o =0 :-O O_O O_o o_O O_0 o_0 0_O 0_o", "O_O"
Smiley = "kiss.gif" , 0, ":-* :* :-{} :{} +{} ={} ^.^ :kiss: *KISS* (K)", ":-*"
Smiley = "cry.gif" , 0, ":'( :'-( :plash:", ":'("
Smiley = "secret.gif", 0, ":-X :-x :-# :# :secret:", ":-X"
Smiley = "aggressive.gif", 0, ">:o >:O >+O >:o >+o :-@ :ranting: :angry:", ">:o"
Smiley = "fool.gif", 0, ":-| :| =| :-S", ":-|"
Smiley = "beee.gif", 0, ":-\ :-/ =\ =/ <_<", ":-\"
Smiley = "mosking.gif" , 0, "*JOKINGLY* 8P 8p", "*JOKINGLY*"
Smiley = "diablo.gif", 0, "]:-> }:-> ]:> }:> >:-] >:] (6) :devil: :diablo: *DIABLO*", "]:->"
Smiley = "music.gif", 0, "[:-} [:} (8)", "[:-}"
Smiley = "air_kiss.gif", 0, "*KISSED* :kissed:", "*KISSED*"
Smiley = "bad.gif", 0, ":-! :! :-~ ;-~ :(~ +(~ =(~ :bad:", ":-!"
Smiley = "boredom.gif", 0, "*TIRED* |-0 :boredom:", "*TIRED*"
Smiley = "stop.gif", 0, "*STOP* STOP!!! :stop:", "*STOP*"
Smiley = "kissing.gif", 0, "*KISSING* :kissing:", "*KISSING*"
Smiley = "give_rose.gif", 0, "@}->-- @}-:-- @>}--,-`--- (F) (f)", "@}->--"
Smiley = "good.gif", 0, "*THUMBS%%_%%UP* :GOOD: :good: GOOD! *GOOD* (Y)", "*THUMBS UP*"
Smiley = "drinks.gif", 0, "*DRINK* DRINK :drink: (B) (D)", "*DRINK*"
Smiley = "heart.gif", 0, "*IN%%_%%LOVE* LOVE (L) :love:", "*IN LOVE*"
Smiley = "bomb.gif", 0, "@=", "@="
Smiley = "help.gif", 0, "*HELP* :help:", "*HELP*"
Smiley = "bull.gif", 0, "\m/", "\m/"
Smiley = "wacko.gif", 0, "%) %-) :-$ :$ :wacko: :WACKO:", "%)"
Smiley = "ok.gif", 0, "*OK* :GOOD: :good: GOOD! *GOOD*", "*OK*"
Smiley = "mamba.gif", 0, "*WASSUP* *SUP*", "*WASSUP*"
Smiley = "sorry.gif", 0, "*SORRY* :sorry:", "*SORRY*"
Smiley = "clapping.gif", 0, "*BRAVO* :bravo:", "*BRAVO*"
Smiley = "lol.gif", 0, "*ROFL* :ROFL: :rofl: ROFL ROFL! rofl LOL lol LoL lOl :lol: *LOL* :megalol: :MEGALOL: l%%%%l L%%%%L", "*ROFL*"
Smiley = "pardon.gif", 0, "*PARDON* :pardon:", "*PARDON*"
Smiley = "no.gif", 0, "*NO* *no* :no:", "*NO*"
Smiley = "crazy.gif", 0, "*CRAZY* :crazy:", "*CRAZY*"
Smiley = "dntknw.gif", 0, "*DONT_KNOW* *UNKNOWN* :dont_know:", "*DONT_KNOW*"
Smiley = "dance.gif", 0, "*DANCE* :dance:", "*DANCE*"
Smiley = "yahoo.gif", 0, "*YAHOO* *YAHOO!* :YAHOO: :yahoo: YAHOO! Yahoo! YAHOO!! Yahoo!! YAHOO!!! Yahoo!!!", "*YAHOO*"
Smiley = "hi.gif", 0, "*HI* *hi* :hi: *PREVED* *preved* *PRIVET* *HELLO*", "*HI*"
Smiley = "bye.gif", 0, "*BYE* *bye* :bye: *BB*", "*BYE*"
Smiley = "yes.gif", 0, "*YES*", "*YES*"
Smiley = "acute.gif", 0, ";D *ACUTE*", "*ACUTE*"
Smiley = "wall.gif", 0, "*WALL* *DASH*", "*WALL*"
Smiley = "scratch.gif", 0, "*SCRATCH*", "*SCRATCH*"

;Smiley = "coffee.gif", 0, "*COFFEE* *coffee* :coffee: *TEA* *CUP*", "*COFFEE*"
